"##############################################################################
" A component of dotme, the dotfile manager.                                  #
"##############################################################################

set nocompatible

set runtimepath=~/.vim,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim-scripts,$VIMRUNTIME,/usr/share/vim-scripts/after,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,~/.vim/after

set autoindent
set autowrite
set background=dark
set backupdir=~/.vim/tmp,.,/tmp
set confirm
set cryptmethod=blowfish
set directory=~/.vim/tmp,.,/tmp
set expandtab
set fileencodings=ucs-bom,utf-8,default,latin1,macintosh
set history=1000
set ignorecase
set modeline
set nofoldenable
set noloadplugins
set pastetoggle=<F11>
set scrolloff=3
set shiftwidth=2
set showcmd
set showmatch
set smartcase
set softtabstop=-1
set tabstop=2
set title
set titlelen=80
set titlestring=%F\ [%{&fileencoding}%Y%R%M]%(\ %a%)
set undodir=~/.vim/tmp,.,/tmp
set undofile
set wildmode=longest,list,full

syntax on

filetype indent on
filetype plugin on

au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
  \| exe "normal g'\"" | endif

highlight RedundantSpaces term=standout ctermbg=yellow guibg=yellow
match RedundantSpaces /\s\+$\| \+\ze\t/

au FileType * set comments=""
au FileType gitcommit set tw<

au FileType html,xhtml,eruby let b:closetag_html_style=1
au Filetype html,xhtml,eruby,xml,xsl ru macros/closetag.vim

au BufRead,BufNewFile Rakefile,Capfile,*.cap,*.ru set filetype=ruby
au BufRead,BufNewFile *.jsonl set filetype=javascript

au FileType ruby set iskeyword+=33,63

au FileType java,groovy set shiftwidth=4

ru! macros/matchit.vim macros/ll.vim plugin/supertab.vim

imap <C-up> <C-x><C-y>
imap <C-down> <C-x><C-e>
nmap <C-up> <C-y>
nmap <C-down> <C-e>

imap <C-left> <ESC>:Next<CR>
imap <C-right> <ESC>:next<CR>
nmap <C-left> <ESC>:Next<CR>
nmap <C-right> <ESC>:next<CR>

noremap  <F12> <ESC>:redraw!<CR>
inoremap <F12> <ESC>:redraw!<CR>a

" <home> toggles between start of line and start of text
imap <khome> <home>
nmap <khome> <home>
inoremap <silent> <home> <C-O>:call Home()<CR>
nnoremap <silent> <home> :call Home()<CR>
function Home()
    let curcol = wincol()
    normal ^
    let newcol = wincol()
    if newcol == curcol
      normal 0
    endif
endfunction

" http://vim.wikia.com/wiki/Faster_loading_of_large_files
let g:LargeFile = 1024 * 1024 * 100
au BufReadPre * let s = getfsize(@%) |
      \ if s < -1 || s > g:LargeFile |
      \ call LargeFile() | endif

function LargeFile()
  " disable syntax highlighting etc.
  set eventignore+=FileType
  " disable writing
  "setlocal buftype=nowrite
  " disable undo
  setlocal undolevels=-1
  " save memory when other file is viewed
  setlocal bufhidden=unload
endfunction

""" LOAD CUSTOM FILE
if filereadable($HOME . "/.vimrc.mine")
  so $HOME/.vimrc.mine
endif
